service: serverless-contact

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  project: contact
  environment:
    GMAIL_ADDRESS: ${file(./serverless.env.yml):dev.GMAIL_ADDRESS}
    GMAIL_PASSWORD: ${file(./serverless.env.yml):dev.GMAIL_PASSWORD}

# plugins:
#   - querystring
#   - nodemailer

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          path: contact
          method: post
          cors: true